version: '3.8'

services:
  host:
    build:
      context: .
      dockerfile: apps/host/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./apps/host:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm dev

  cue:
    build:
      context: .
      dockerfile: apps/cue/Dockerfile
    ports:
      - "5174:5174"
    volumes:
      - ./apps/cue:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm dev

  react-remote:
    build:
      context: .
      dockerfile: apps/react-remote/Dockerfile
    ports:
      - "5175:5175"
    volumes:
      - ./apps/react-remote:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm dev

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - host
      - cue
      - react-remote

networks:
  default:
    name: micro-frontend-network